name:                hsprocessing
version:             0.1.0.0
synopsis:            NodeLab
homepage:            www.nodelab.io
author:              New Byte Order
maintainer:          contact@nodelab.io
category:            drag and drop test, all reactive

default-extensions: NoImplicitPrelude
                    DoAndIfThenElse
                    TemplateHaskell
                    DeriveGeneric
                    StandaloneDeriving
                    FlexibleContexts
                    MultiParamTypeClasses
                    DefaultSignatures
                    DeriveFunctor
                    DeriveTraversable
                    DeriveFoldable
                    FlexibleInstances
                    LambdaCase
                    ConstraintKinds
                    GeneralizedNewtypeDeriving
                    DeriveDataTypeable
                    ScopedTypeVariables
                    KindSignatures
                    DataKinds
                    TypeFamilies
                    QuasiQuotes
                    TupleSections

dependencies:        base >= 4.8 && < 4.9
                   , lens
                   , mtl
                   , transformers
                   , prologue
                   , language-glsl
                   , parsec
                   , template-haskell
                   , convert
                   , prettyclass
                   , vector
                   , data-rtuple
                   , data-repr
                   , typelevel
                   , split

library:
  source-dirs:        src
  default-language:   Haskell2010

executables:
  hsprocessing-test:
    main:             Main.hs
    source-dirs:      test
    dependencies:
      - hsprocessing
